services:
  backend:
    build:
      context: ./backend
    image: my-backend-image
    container_name: backend-container
    ports:
      - "8000:8000"
    networks:
      - my-network

  frontend:
    build:
      context: ./frontend
    image: my-frontend-image
    container_name: frontend-container
    ports:
      - "8501:8501"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
